### ISSUE TITLE
✨ Support .NET 6

### ISSUE THREAD

**Issue by ecampidoglio** [AutoFixture/AutoFixture#1354]
### Description

AutoFixture ought to keep up with the times and add support for .NET 6.

### Tasks

- [x] Get all solutions to build on the .NET 6 SDK #1448 
- [x] Update the build on GitHub Actions #1448 
- [x] Add support for `DateOnly` and `TimeOnly` #1453 

Feel free to add more tasks as you see fit.

**Comment by EdCharbeneau** [comment]
.NET 8 is coming next month. Is this project still being maintained?

**Comment by Kralizek** [comment]
@aivascu how about using github packages for the previews? at least we could push to nuget previews and not artifacts from every build.

**Comment by aivascu** [comment]
@Kralizek, it's a good idea in the sense that there's no storage limit for oss packages, unlike MyGet. However, I wasn't planning on publishing packages on every build, only tagged releases.
The reason for moving preview packages to NuGet is that no one bothers to add the MyGet feed to use the available previews.
Perhaps we could get some use out of GitHub packages with branch releases?

**Comment by Kralizek** [comment]
I was thinking about non tagged packages for GHP as well.

So tagged previews and release packages go to nuget, everything else to GHP.

**Comment by aivascu** [comment]
Support for .NET 6 and `DateOnly`, `TimeOnly` structs are now available as part of `v5.0-preview011`.
Additional requests related to .NET 6 will be implemented as separate requests/issues.
