### ISSUE TITLE
✨ Support FakeItEasy 8

### ISSUE THREAD

**Issue by mattiasnordqvist** [AutoFixture/AutoFixture#1413]
### Description
It would be great if AutoFixture.FakeItEasy supported FakeItEasy 8
![image](https://github.com/AutoFixture/AutoFixture/assets/5485546/416c6cd6-78de-4454-a2eb-4fba96f04643)

### Tasks

- [ ] Investigate relevant breaking changes in fakeiteasy
- [ ] Adjust autofixture.fakeiteasy accordingly
- [ ] Ship with new package constraints

### More Information
- 

Thanks!

**Comment by aivascu** [comment]
If there are no blockers I'll try to get an update in a day or two. Last time there were some issues opening the constraint on the versions AFAIR.
