### ISSUE TITLE
Add Release Notes for v4

### ISSUE THREAD

**Issue by zvirja** [AutoFixture/AutoFixture#888]
Add a wiki  article with release notes for v4. The following issues should be mentioned (sorted by priority).

Breaking changes:
- [x] Remove the 'Ploeh' namespace prefix (#745)
- [x] Move all Create overloads taking a seed to another library (#151)
- [x] NUnit3: Make `FixedNameTestMethodBuilder` the default strategy (#862)
- [x] RandomRangedNumberGenerator should be the default handler of RangedNumberRequest (#213)

New features:
- [x] Support .NET Core (#404)
- [x] Rework NSubstitute integration approach (#832)
- [x] Support for `IReadOnlyCollection` (#257)
- [x] Add `IParameterCustomizationSource` interface to AutoFixture project (#842)
- [x] Implement SourceLink approach to enable simpler source code stepping (#770)

Enhancements:
- [x] [Performance] Make fixture creation lazy in AutoData attribute (#843)
- [x] Extract SemanticComparision to a standalone repo (#833)
- [x] Improve exception handling by showing full request path on failure (#787)
- [x] Add guard to fail fast when nested members used during customization (#837)
- [x] Check parameter name in GuardClauseAssertion (#258)
- [x] Merge AutoFixture.NUnit2.Addins to AutoFixture.NUnit2 (#785)
- [x] Make some InlineAutoDataAttribute constructor overloads protected (#458)
- [x] Make some AutoData constructor overloads protected (#532)
- [x] Remove implicit 'assignable from' match from ConstructorInitializedMemberAssertion (#207)
- [x] Set upper boundary for external dependencies (#844)
- [x] AutoFixture.AutoFoq should use Foq's new Return Strategy (#214)
- [x] Add guard dependencies to xUnit and NUnit2 integrations (#835)
- [x] Remove Request from NoSpecimen (#475)

Bug fixes:
- [x] Fix one customization could affect other customizations (#781)
- [x] Passive Customization Attributes are ignored when used in combination with [Frozen] (#637)
- [x] Cast operators shouldn't be used as factory method during specimen construction (#691)
- [x] Fix RandomRangedNumberGenerator fails on very large ranges (#840)
- [x] Sort customization attributes for InlineAutoData for NUnit3 glue library (#854)
- [x] Add null guards for request and context in fixture.Create() (#872)

**Comment by zvirja** [comment]
Done. Link: https://github.com/AutoFixture/AutoFixture/wiki/v4.0-Release-Notes
