### ISSUE TITLE
v4 RTM Release

### ISSUE THREAD

**Issue by zvirja** [AutoFixture/AutoFixture#955]
Here is the list of actions required to prepare for the v4 release.

Preparations:
- [x] Close all the PRs for `master` and freeze changes to the `master` branch till the release.
- [x] Close all the issues and PRs in the [v4 milestone](https://github.com/AutoFixture/AutoFixture/milestone/4).
- [x] Collect all the important v4 changes since v4 RC1.
- [x] Update the breaking changes document on Wiki.
- [x] Review `Contributing.md` and wiki and ensure no obsolete information is present there.

Release:
- [x] Release AutoFixture `v4.0.0`.
- [x] Make a tweet.
- [x] Thank to everybody who participated 😉

Important Changes
----------
- [x] DataAnnotations RangeAttribute causes arithmetic OverflowException #453
- [x] Improve ObjectCreationException wrapping with full path #892
- [x] Obsolete RandomRangedNumberCustomization #899
- [x] Ranged request fails if request has same min and max #897
- [x] Return ISpecimenBuilderNode in ISpecimenBuilderTransformation #905
- [x] [xUnit/xUnit2] Loosen up InlineAutoDataAttribute constructor to take DataAttribute argument #911
- [x] Allow to relay open generic types via TypeRelay #936 / Handle open generics by ExactTypeSpecification and remove redundancies #935
- [x] Change ModestConstructorQuery behavior to skip copy constructors #918
- [x] Introduce RangedRequest to support non-number types #920
- [x] Range attribute on Enum throws InvalidCastException #722
- [x] Resolve `IReadOnlyList<>` out of the box #924
- [x] Move `NoDataAnnotationsCustomization` to `DataAnnotations` namespace #957

**Comment by emanuelmarques** [comment]
Hello @zvirja 
Is there an estimated date for the v4 to be available in nuget?

**Comment by zvirja** [comment]
Hi @emanuelmarques I expect to release it somewhere during the upcoming weeks. Are you waiting for some particular feature? We already have RC released with all the major changes applied, so it should cover most of your needs..

**Comment by emanuelmarques** [comment]
Some company policies dictate to avoid the use of pre-release packages. However, I already tested it for my needs and it is working :)

**Comment by zvirja** [comment]
@moodmosaic All the preparations has been finished and I'm ready for the v4 RTM release (finally 😄).  I believe that I applied all the breaking changes I wanted. All the breaking changes we might need in future will go to v5.

I'm going to proceed with the release tomorrow - let me know if you have any concerns 😉

**Comment by moodmosaic** [comment]
Go ahead 👍 🚀 🥇 💯

**Comment by zvirja** [comment]
v4 RTM is finally there. This is the first stable major release since the ownership has been passed. It's great that we can make this project alive! 🎉

Thanks to everybody who contributed to the project since v4 RC1 (@Kralizek, @Loppor, @micheleissa, @rexcfnghk and others) - you help our project be healthy and shine brighter! 🙏🤝  

@moodmosaic The traditional "thanks" for your code reviews and the expertise you provided during the development 🍷

**Comment by emanuelmarques** [comment]
thank you so much @zvirja and everyone else who contributed :)

**Comment by zvirja** [comment]
@frblondin Given that AutoFixture v4 has been finally published, would you be fine to unlist the [AutoFixture.NUnit3.PatchedName](https://www.nuget.org/packages/AutoFixture.NUnit3.PatchedName/) package? It doesn't seem to be required anymore 😉

**Comment by frblondin** [comment]
@zvirja I unlisted all [AutoFixture.NUnit3.PatchedName](https://www.nuget.org/packages/AutoFixture.NUnit3.PatchedName/) package versions.

I think people can barely imagine the effort and time it represents to deliver such a great library! Congratulation and great job for v4 final.

**Comment by zvirja** [comment]
@frblondin Thanks a lot for the graceful words! 🙏 It indeed takes huge amount of time and it's warm to read such kind of feedback ☺️

**Comment by rexcfnghk** [comment]
Thank you for the effort to get it out of the door @zvirja !
